### ISSUE TITLE
How to change wake up word?

### ISSUE THREAD

**Issue by davorf** [hey-athena/hey-athena-client#40]
Could you please tell me how to change wake up word in Athena? Since the English is not my native language, I would like to change wake up word to something easier to pronounce (without th phoneme in it). I found WAKE_UP_WORD in settings.py, but changing it to something else doesn't work (after changing it, Athena doesn't wake up at all - with any word, old or new). I've seen a comment inside a code that says I must use word that's in sphinx dictionary, but I don't know how to add or even see a list of words in Sphinx dictionary. I've tried using common words, like Computer or Sarah. Anyway, Athena works really good, and the best thing is flexibility and it's modular nature. Keep up the good work.

Thank you in advance,
Davor

**Comment by rcbyron** [comment]
Hi Davor,

Thanks for your feedback. I just added "athena.dict" in the "athena/data" folder (on the GitHub package, not PyPI). You can use that to add your custom wake-up-word or phrase. 
To use this, be sure to change the pronunciation dict in settings.py:
``POCKET_DICT = join(DATA_DIR, 'athena.dict')``

Here is the default dict (hopefully you can use this as reference to figure out your wake-up-word transcription).

https://raw.githubusercontent.com/Uberi/speech_recognition/master/speech_recognition/pocketsphinx-data/en-US/pronounciation-dictionary.dict

Let me know if that helps!

Connor

**Comment by davorf** [comment]
Thank you for the information. That was exactly what I was looking for.

Best regards,
Davor
